# render.yaml
# This file configures a simple web service for the mp4-to-gif-converter on Render.
# NOTE: This architecture does NOT use a background worker and may face timeout issues.

services:
  # A single Web Service (Flask/Gunicorn)
  # This service runs your Flask application.
  - type: web
    name: mp4-to-gif-web
    runtime: python
    plan: free
    # Command to install dependencies from your requirements file
    buildCommand: "pip install -r mp4-to-gif-converter/webapp/requirements.txt"
    # Command to run the Gunicorn server
    # CRITICAL: Use 1 worker and multiple threads to share state in memory/filesystem.
    startCommand: "gunicorn --chdir mp4-to-gif-converter/webapp app:app --workers 1 --threads 8 --timeout 120"
    envVars:
      # Set Python version via environment variable as a workaround
      - key: PYTHON_VERSION
        value: "3.10"
      # FFMPEG_PATH and FFPROBE_PATH are available in Render's standard environment,
      # so we don't need to set them explicitly.
      # Add the project folder to the Python path.
      - key: PYTHONPATH
        value: ./mp4-to-gif-converter